steps:
      # Install
      - name: 'gcr.io/cloud-builders/npm'
        args: ['install']
      #DEV
      #- name: 'gcr.io/cloud-builders/npm'
      #  args: ['run', 'dev']
      # Build
      - name: 'gcr.io/cloud-builders/npm'
        args: ['run', 'build']
      # Deploy
      - name: gcr.io/project-id/firebase
        args: ['deploy', '--project=pcicd-demo-3f04d', '--only=hosting']